# Generated by Django 5.0 on 2024-01-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paticipant',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=500)),
                ('project_photo', models.ImageField(upload_to='')),
                ('prepared_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Viewers',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
