# Generated by Django 5.0 on 2024-01-28 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewers',
            options={'verbose_name_plural': 'Viewers'},
        ),
        migrations.RenameField(
            model_name='paticipant',
            old_name='name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='viewers',
            old_name='name',
            new_name='username',
        ),
    ]
