# Generated by Django 5.0 on 2024-01-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_alter_viewers_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewers',
            name='email',
        ),
        migrations.AlterField(
            model_name='viewers',
            name='username',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
